apiVersion: v1
kind: Service
metadata:
  name: kube-node-deploy6
  labels:
    app: kube-test
spec:
  ports:
    - port: 80
      targetPort: 80
      name: http
  selector:
    app: kube-test
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-node-deploy6
spec:
  selector:
    matchLabels:
      app: kube-test
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-test
    spec:
      containers:
        - name: node-container
          image: kubetest4.azurecr.io/kube-test
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: kubetest4
